### PR TITLE
feat: added support for clickhouse

### PR DESCRIPTION
**Pull request by stephenafamo**

### CODE REVIEW

**Comment by kndndrj** [comment]
@stephenafamo  I see that you updated for refactor. Thanks a lot! I'll go over the code and point out (or fix) if I fknd anything obvious.

Other than that I trust that you tested it yourself and it is working.

**Comment by stephenafamo** [comment]
Yes, I've tested locally and it works.

However, I do get an error while trying to open some **Postgres connections** of the form. Interestingly, this does not happen for all connections

image

**Comment by kndndrj** [comment]
hmm, at a glance it looks like an issue with either pq or local file system permissions.

If you want you can try to recreate the issue with minimal go program :). Otherwise if the issue persists, you can create an issue here on github.

**Review by kndndrj — APPROVED** [review]
looks good - don't know the details of clickhouse, so I leave that to trust :D

**Pull request merged**
