### PR TITLE
Minimal windows support

### LINKED ISSUE #129: Errors on windows
os: Windows 11
nvim version: v0.10.0
shell: windows cmd

running `:Dbee open` or `:Dbee toggle` on windows causes this error:

bilde

I've tried different installers, but the issue seems to be missing compatability with windows.
I saw a previous issue (#51) mentions errors on windows, but since that issue is rather outdated and the errors have changed, I thought I would create a new issue. Are there any plans for windows support?

### PR DESCRIPTION
**Pull request by adament**
Add support for Windows fixes #129 on my machine.

### CODE REVIEW

**Comment by kndndrj** [comment]
Does this actually work? I'm asking, because I see that path separators are still "/"... Does lua do some magic internally?

**Comment by adament** [comment]
Yes surprisingly it works on at least on my Windows machine, I think it is less lua or neovim doing magic and more Windows actually treating forward slash as a path separator. https://retrocomputing.stackexchange.com/questions/28344/since-when-does-windows-support-forward-slash-as-path-separator

**Comment by kndndrj** [comment]
Damn... the future is NOW

**Comment by kndndrj** [comment]
given that the ammount of changes is minimal and you tested it, I'll just merge this.

Thanks

**Pull request merged**
